version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: bioren
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
