version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: bioren
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  bioren-backend:
    build: .
    depends_on:
      - mariadb
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    command: ["java", "-jar", "target/bioren_backend-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=prod"]

volumes:
  mariadb_data:
